### ISSUE TITLE
prior distribution

### ISSUE THREAD

**Issue by afrooze** [tminka/fastfit#1]
Hi,
 I read your inspirational paper "Estimating a Dirichlet distribution " and I'm very keen on using your work in my thesis.
can you explain to me how can calculate prior distribution by Dirichlet distribution
Best regards

**Comment by tminka** [comment]
Sorry, I don't understand the question.

**Comment by afrooze** [comment]
hi,
Dear Dr.Minka
thanks for your attention. I have a directed graph with the label. can you explain to me how to compute Prior Dirichlet for each node? I need to use the Prior Dirichlet in MAP.
I read your paper about the Dirichlet distribution and I keen to use it in my work.

**Comment by tminka** [comment]
That is not enough information.  What data do you have?

**Comment by afrooze** [comment]
I am working on knowledge graph and my dataset is free base.
https://pypi.org/project/pykg2vec/

**Comment by tminka** [comment]
How are you planning to model that data, so that a Dirichlet would be involved?

**Comment by afrooze** [comment]
I will use a GMM model in my work and I am going to use MAP for linkprediction in GMM model. the MAP is prior*likelihood and i compute Dirichlet for prior and likelihood. i am doing this beacause last papers only count the number of edges and it leads to eliminate some of nodes. 
is it possible to use Dirichlet just for Prior?? can i use a kernel similarity for likelihood?? I know that if i use this method, the type of prior and likelihood are not same, but I am not sure it  work truly for MAP.

**Comment by tminka** [comment]
Do you have a paper describing the intended system in more detail?

**Comment by afrooze** [comment]
a translation based method: (https://www.aclweb.org/anthology/Y14-1039.pdf) 
a pointwise based method:(http://proceedings.mlr.press/v48/trouillon16.html)
I need define a new Score function in my thesis. a Dirichlet combine function in MAP is my proposal. my work is a pointwise based method.

**Comment by tminka** [comment]
These papers do not use Dirichlet distributions, so they do not clarify your intent.

**Comment by afrooze** [comment]
Dear Dr.Minka
I want to used from  Dirichlet distributions for first time. this method is not used before this

**Comment by tminka** [comment]
Right, and so if you are asking for my advice, you need to explain what you want to do, which is why I asked for a write-up of the intended system, where "intended" means "using a Dirichlet distribution".

**Comment by afrooze** [comment]
Dear Dr.Minka
https://dl.acm.org/doi/10.1145/2806416.2806502
This paper used from an energy function. This function is based on comparing two Gaussian probabilities: head-tail probability and relation probability. But, i am going to use from Bayesian probability score function for each asked triple (head-relation-tail) to compute how much is the occurrence probability of triple. So, P(h,r,t) must be calculate by Bayesian estimation and P(h,r,t’)=P(h,t’|r)*P(r) or  P(h,r’,t)=P(h,r’|t)*P(t). r’ or t’ is asked object. I can compute P(t) or P(r) by enumeration but it is not acceptable for big data (I cannot set a specific distribution) so p(h,r|t) and P(t) can be compute by Dirichlet distribution.

**Comment by tminka** [comment]
I still don't see how Dirichlet distributions enter it.  The paper embeds in a vector space and uses a Gaussian distribution over those vectors.  Are you planning to replace the Gaussian with Dirichlet in the energy-function formulation?

**Comment by afrooze** [comment]
yes,exactly. but I dont know  how can do it. can you guide me about that?

**Comment by tminka** [comment]
You cannot use this library to do energy-function minimization.  It only does maximum-likelihood learning.

**Comment by afrooze** [comment]
can you explain to me how can do it?

**Comment by tminka** [comment]
No, that is too far outside the scope of this repository.  A question like that is better asked on [Cross Validated](https://stats.stackexchange.com/).
